version: "3.5"
services:
  postgres:
    image: postgres:latest
    container_name: "yanlex-wow-guild-postgres"
    volumes:
     - yanlex-wow-guild-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    ports:
      - "5432:5432"
    networks:
      - wowguild

volumes:
  yanlex-wow-guild-postgres:
    name: yanlex-wow-guild-postgres

networks:
  wowguild:
    driver: bridge
    external: true
    name: wowguild