# Конфигурация приложения wow-guild-website
guild:
  raiderio_api_url: "https://raider.io/api/v1/guilds/profile?region=eu&realm=howling-fjord&name=%D0%9A%D0%BB%D1%8E%D1%87%D0%B8%D0%BA%20%D0%B2%20%D0%B4%D1%83%D1%80%D0%BA%D1%83&fields=members"
db:
  url: "postgres://user-name:strong-password@localhost:5432"
  urlKvd: "postgres://user-name:strong-password@localhost:5432/kvd_guild"
dbCreateStructure:
  dbName: "kvd_guild"

